### ISSUE TITLE
Cannot create SingleCellExperiment object

### ISSUE THREAD

**Issue by qq2006tom-cmd** [rikenbit/scTensor#10]
Dear developer,

I am a new R user. I follow the online scTensor tutorial to analyze the 10x Genomics data from pig. After I convert 'SYMBOL' to 'NCBI ID', I cannot create SingleCellExperiment object. If I don't do the conversion, there is not any problem. Could you help me to figure it out? Thank you.

R version 3.6.2
scTensor version 1.2.1

> pc.data <- Read10X(data.dir = ".\\filtered_feature_bc_matrix\\")
> for_sc <- as.matrix(pc.data)
> rowID <- rownames(for_sc)
> LefttoRight <- select(org.Ss.eg.db, column=c("SYMBOL", "ENTREZID"), keytype="SYMBOL", keys=rowID)
##'select()' returned 1:many mapping between keys and columns
> for_sc <- convertToNCBIGeneID(for_sc, rowID, LefttoRight)
11563 of genes are removed from input matrix (25880*3011),
and only 14317 of genes are kept.
> pc <- CreateSeuratObject(counts = for_sc, project = "pc", min.cells = 3, min.features = 200)
> pc <- NormalizeData(pc, normalization.method = "LogNormalize", scale.factor = 10000)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> pc <- data.matrix(pc, rownames.force = NA)
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector
> pc <- as.matrix(GetAssayData(pc, slot = "counts"))
> sce <- SingleCellExperiment(assays=list(counts = pc))
Error in validObject(.Object) : 
  invalid class "SummarizedExperiment" object: 
    'names(x)' must be NULL or a character vector with no attributes
> names(pc)
NULL
> sce <- as.SingleCellExperiment(pc)
Error in UseMethod(generic = "as.SingleCellExperiment", object = x) : 
  no applicable method for 'as.SingleCellExperiment' applied to an object of class "c('matrix', 'double', 'numeric')"

**Comment by kokitsuyuzaki** [comment]
Hi, 

I still not understand the details, but it might be caused by using Seurat functions/objects and those of R/Bioconductor packages together.
If you want to use scTensor, you should convert SingleCellExperiment at first, and should not use Seurat's functions.

```r
sce <- SingleCellExperiment(assays=list(counts = for_sc))
```

The log-normalization is still available by other R/Bioconductor packages such as scater, scran
https://bioconductor.org/packages/release/bioc/vignettes/SingleCellExperiment/inst/doc/intro.html
https://bioconductor.org/packages/3.10/bioc/vignettes/scran/inst/doc/scran.html
https://bioconductor.org/packages/3.10/bioc/vignettes/scater/inst/doc/overview.html

and acutally you can perform such normalization from scratch.

```r
normcounts(sce) <- log10(counts(sce) + 1)
```

Koki

**Comment by qq2006tom-cmd** [comment]
Hi Koki,

Thank you for your help.

This time I tried to use DropletUtils to input my 10X genomics data. However, the rownames are 'ENSEMBL', which is not the keytypes of org.ss.eg.db (pig). I don't know how to convert ensembl to entrezid. In addition, I cannot do the normalization from scratch or scater. I don't know if I miss something. I really hope you can help me out. Thank you very much.

Tao

>BiocManager::install("DropletUtils")
>library("DropletUtils")
>pc.data <- read10xCounts(".\\filtered_feature_bc_matrix\\")
>pc.data
class: SingleCellExperiment 
dim: 25880 3011 
metadata(1): Samples
assays(1): counts
rownames(25880): ENSSSCG00000037372 ENSSSCG00000027257 ... ENSSSCG00000036779
  ENSSSCG00000034846
rowData names(3): ID Symbol Type
colnames: NULL
colData names(2): Sample Barcode
reducedDimNames(0):
spikeNames(0):
altExpNames(0):
>sce <- SingleCellExperiment(assays=list(counts = pc.data))
> sce
class: SingleCellExperiment 
dim: 25880 3011 
metadata(0):
assays(1): counts
rownames(25880): ENSSSCG00000037372 ENSSSCG00000027257 ... ENSSSCG00000036779
  ENSSSCG00000034846
rowData names(0):
colnames: NULL
colData names(0):
reducedDimNames(0):
spikeNames(0):
altExpNames(0):
>suppressPackageStartupMessages(library("AnnotationHub"))
> ah <- AnnotationHub()
> ss <- query(ah, c("OrgDb", "Sus scrofa"))[[1]]
>keytypes(ss)
[1] "ACCNUM"      "ALIAS"       "ENTREZID"    "ENZYME"      "EVIDENCE"    "EVIDENCEALL"
 [7] "GENENAME"    "GO"          "GOALL"       "ONTOLOGY"    "ONTOLOGYALL" "PATH"       
[13] "PMID"        "REFSEQ"      "SYMBOL"      "UNIGENE"     "UNIPROT"  
> rowID <- rownames(sce)
> LefttoRight <- select(ss, column=c("ENSEMBL", "ENTREZID"), keytype="ENSEMBL", keys=rowID)
Error in testForValidKeytype(x, keytype) : 
  Invalid keytype: ENSEMBL. Please use the keytypes method to see a listing of valid arguments.
> normcounts(sce) <- log10(counts(sce) + 1)
Error in counts(sce) + 1 : non-numeric argument to binary operator

**Comment by kokitsuyuzaki** [comment]
Hi,

Yes, I heard my friend also found that some AnnotationHub packages (e.g. Tomato) have no specific gene identifiers.
Probablity your case is also this unlucky case.
How about biomaRt?

```r
library("biomaRt")
db <- useMart("ensembl")
ss <- useDataset("sscrofa_gene_ensembl", mart = db)

# ensid is your Ensembl Gene ID
res <- getBM(attributes = c("ensembl_gene_id", "entrezgene_id"),
             filters = "ensembl_gene_id", 
             values = ensid,
             mart = ss)
```

The error message "Error in counts(sce) + 1 : non-numeric argument to binary operator" seems same as the error message when performing 1 + "A".

Is this counts(sce) numerical matrix?

**Comment by qq2006tom-cmd** [comment]
Hi Koki,

I tried your method, and I can get the pair of entrezgene_id and ensembl_gene_id.
`head(res)

     ensembl_gene_id entrezgene_id
1 ENSSSCG00000004008     100736968
2 ENSSSCG00000004009     102162319
3 ENSSSCG00000004010     100512199
4 ENSSSCG00000004012     100153940
5 ENSSSCG00000004013     100737228
6 ENSSSCG00000004016            NA
`
However, when I used 'res' to do 'convertToNCBIGeneID', I got the following error message.

`library("DropletUtils")

pc.data <- read10xCounts(".\filtered_feature_bc_matrix\")

pc.data

sce <- SingleCellExperiment(assays=list(counts = pc.data))

rowID <- rownames(sce)

sce <- convertToNCBIGeneID(sce, rowID, res)

Error in as.vector(x) : no method for coercing this S4 class to a vector
`

When I used 'pc.data' as input to do normalization, I didn't get the error. But 'sce' did. Both are SingleCellExperiment object.

`pc.data

class: SingleCellExperiment 
dim: 25880 3011 
metadata(1): Samples
assays(1): counts
rownames(25880): ENSSSCG00000037372 ENSSSCG00000027257 ... ENSSSCG00000036779
  ENSSSCG00000034846
rowData names(3): ID Symbol Type
colnames: NULL
colData names(2): Sample Barcode
reducedDimNames(0):
spikeNames(0):
altExpNames(0):

sce

class: SingleCellExperiment 
dim: 25880 3011 
metadata(0):
assays(1): counts
rownames(25880): ENSSSCG00000037372 ENSSSCG00000027257 ... ENSSSCG00000036779
  ENSSSCG00000034846
rowData names(0):
colnames: NULL
colData names(0):
reducedDimNames(0):
spikeNames(0):
altExpNames(0):
`

**Comment by kokitsuyuzaki** [comment]
The input of convertToNCBIGeneID is a matrix and not SingleCellExperiment object,
so please perform like this

```r
sce <- convertToNCBIGeneID(counts(sce), rowID, res)
```

**Comment by qq2006tom-cmd** [comment]
Hi Koki,

It works. Thank you so much for your help. I really appreciate it. I will continue to do the following steps. If I have further questions, I will start a new issue. Thanks again.

Tao

**Comment by skim245** [comment]
Hi Koki, 

I also have similar issue, after converting gene SYMBOL to ENTREZID, I cannot convert the matrix to SingleCellExperiment object. 

sce <- SingleCellExperiment(assays=list(counts = for_sc))
Error in validObject(.Object) : 
  invalid class "SummarizedExperiment" object: 
    'names(x)' must be NULL or a character vector with no attributes

Suzy
