### ISSUE TITLE
cellCellSetting problem

### ISSUE THREAD

**Issue by qq2006tom-cmd** [rikenbit/scTensor#11]
Hi Koki,

I know this issue has been asked, but I have no idea how to solve that. So I start a new one. 

I don't exactly know how you can generate the color vector of each cell and cell type vector of each cell. What I did is that I exported the cell labels and cell color to .csv file based on the analysis using Seurat. 

Cell                                     Cell_type              Color
AAACCCAAGTCCCAGC | Endothelial cells | #BE9C00
AAACCCACAATACAGA | T cells                 | #8CAB00
AAACCCAGTATACCTG | Smooth muscle cells | #24B700
AAACCCAGTGGAATGC | Endothelial cells | #BE9C00

I used 'Cell_type' and 'Color' as input of cellCellSetting. I got the error like this:

`> cellCellSetting(sce, LRBase.Ssc.eg.db, LC$Color, LC$Cell_type)

Error in .cellCellSetting(userobjects, lrbase, color, label, sce) : 
  Please specify the color as the vector which has
            same length of nrow(assay(sce))
`

The related info is as follows:

`> nrow(assay(sce))
[1] 17347
> ncol(assay(sce))
[1] 2276
> length(LC$Color)
[1] 2229
> length(LC$Cell_type)
[1] 2229
`

Can you help me to figure this out? Thank you.

Tao

**Comment by kokitsuyuzaki** [comment]
Hi, Tao

As the error message said, this is because the size of ncol(assay(sce)), length(LC$Color), and length(LC$Cell_type) are not same.

I don't know the details of Seurat process, but perhaps some low-quality cells were removed in Seurat automatically or manually.
Please confirm it and unify the sizes.
Using the 2229 cells in all the analyses might be better.

**Comment by qq2006tom-cmd** [comment]
Hi Koki,

I managed to get the same cell number. But I have another issue. 

`> cellCellSetting(sce, LRBase.Ssc.eg.db, LC$Color, LC$Cell_type)
Error in .cellCellSetting(userobjects, lrbase, color, label, sce) : 
  Please specify the row names of the input matrix is unique
> nrow(assay(sce))
[1] 17347
> nrow(unique(assay(sce)))
[1] 13560
`
I tried to subset 'sce' using 'rownames(unique(assay(sce)))', but still cannot make it. Could you please give me some advice. Thank you.

Tao

**Comment by kokitsuyuzaki** [comment]
Could you show me the results of this script?

```
head(rownames(counts(sce)))
length(rownames(counts(sce)))
length(unique(rownames(counts(sce))))
```

**Comment by qq2006tom-cmd** [comment]
Here are the results.

> head(rownames(counts(sce)))

[1] "100621969" "100620583" "100620481" "100512199" "102162319" "100511109"

> length(rownames(counts(sce)))

[1] 17347

> length(unique(rownames(counts(sce))))

[1] 17312

**Comment by kokitsuyuzaki** [comment]
Ok, this might be the error of convertNCBIGeneID().
I recently re-implemented almost same function **convertRowID()** in scTGIF package.
You will see the options are also almost same.
Could you try this function?
You can download it from this repository.
https://github.com/rikenbit/scTGIF

```r
install.packages("devtools", repos="http://cran.r-project.org")
library(devtools)
devtools::install_github("rikenbit/scTGIF")
```

**Comment by qq2006tom-cmd** [comment]
I tried to use convertRowID() in scTGIF package, but I failed. I don't know why this happened. Please advise.

`
>BiocManager::install("scTGIF")
>library(scTGIF)
> sce <- convertRowID(sce, rowID, res, "mean")
Error in convertRowID(sce, rowID, res, "mean") : 
  could not find function "convertRowID"
> packageVersion("scTGIF")
[1] ‘1.2.0’
`

**Comment by kokitsuyuzaki** [comment]
Sorry, I've not uploaded the new scTGIF to BioC yet,
so download scTGIF directly from our GitHub repository like below:

```r
install.packages("devtools", repos="http://cran.r-project.org")
library(devtools)
devtools::install_github("rikenbit/scTGIF")
```

**Comment by qq2006tom-cmd** [comment]
When I ran the following script

`sce <- convertRowID(counts(sce), rowID, res, "mean")`

I got the error message:  'x' must be an array of at least two dimensions.

Then I changed the class of matrix and re-ran the script.

`counts(ace) <- as.matrix(counts(ace))

sce <- convertRowID(counts(sce), rowID, res, "mean")

Input matrix: 17347x2276
Output matrix: 17716x2276
Some gene expression vectors were collapsed into single vector
  by mean rule
`

Although there is no error, the class(sce) is "list", not "SingleCellExperiment". The sce looks like this:

[17713,] "ENSSSCG00000040853"                                                                "110259193"
[17714,] "ENSSSCG00000040873"                                                                "100524875"
[17715,] "ENSSSCG00000040928"                                                                "110258931"
[17716,] "ENSSSCG00000040963"                                                                "110258254"

There are not any counts and Sample Barcodes. 

I don’t know why this happened. Please advise. Thank you.

**Comment by kokitsuyuzaki** [comment]
Hi, Tao

Oh sorry, the usage of convertRowID() and convertNCBIGeneID() are almost same,
the output of convertRowID() is slightly different; the output is a list containing two elements like below.

```r
out <- convertRowID(counts(sce), rowID, res, "mean")
head(out$output)
head(out$ctable)
```

So, please use out$output as the matrix with NCBI Gene ID.

https://github.com/rikenbit/scTGIF/blob/230c13e52a06b24bcb09fe5fdf539b6d6f3a67e3/R/convertRowID.R#L156

Koki

**Comment by qq2006tom-cmd** [comment]
Hi Koki,

Thank you very much for your help.  The 'cellCellSetting' problem has been solved. 

But when I ran cellCellReport, I got a [warning]:
This document format requires a nonempty <title> element. Please specify either 'title' or 'pagetitle' in the metadata. Falling back to 'ligand_all.utf8', 

and also a ERROR: 
Quitting from lines 105-108 (index.Rmd) 
Error in UseMethod("toPaletteFunc") : no applicable method for 'toPaletteFunc' applied to an object of class "factor".

Could you please tell me how to fix them? Thanks a lot

Tao

**Comment by kokitsuyuzaki** [comment]
I'm not sure what was happened.
If possible, could you send me your data and source code to reproduce the error in my PC?
My E-mail address is koki.tsuyuzaki [at] gmail.com

**Comment by kokitsuyuzaki** [comment]
Hi, Tao

I finally found out the reason for the error.
Please try this script.

```r
library("DropletUtils")
library("biomaRt")
library("scTGIF") # v-1.2.0 or higher
library("scTensor") # v-1.2.0 or higher
library("LRBase.Ssc.eg.db")
library("Rtsne")
library("MeSH.Ssc.eg.db")

# Data loading
data <- read10xCounts("filtered_feature_bc_matrix", col.names=TRUE)
LC <- read.csv("data with celltype and color.csv", stringsAsFactors=FALSE)
target <- which(LC$Cell_type == "Mitochondria of eukaryotic\xa0cells") # <- Should remove \xa0 !!!
LC$Cell_type[target] <- "Mitochondria of eukaryotic 0cells"

# preprocess
colnames(data) <- gsub("-1", "", colnames(data))

# filtered some cells
data <- data[, LC$UMI]
counts(data) <- as.matrix(counts(data))
normcounts(data) <- log10(counts(data) + 1)

# Ensembl
rowID <- rownames(data)
db <- useMart("ensembl")
ss <- useDataset("sscrofa_gene_ensembl", mart = db)
res <- getBM(attributes = c("ensembl_gene_id", "entrezgene_id"),
    filters = "ensembl_gene_id", values = rowID, mart = ss)

# ID conversion
out <- convertRowID(counts(data), rowID, res, "mean")

# SingleCellExperiment
sce <- SingleCellExperiment(assays=list(counts = out$output))
normcounts(sce) <- log10(counts(sce) + 1)

# t-SNE
set.seed(123)
tsnesce <- Rtsne(dist(t(counts(sce))), is_distance=TRUE, perplexity=40)

# scTensor
cellCellSetting(sce, LRBase.Ssc.eg.db, LC$Color, LC$Cell_type)
reducedDims(sce) <- SimpleList(TSNE=tsnesce$Y)
cellCellDecomp(sce, ranks=c(3,3))
tmp <- tempdir()
cellCellReport(sce, reducedDimNames="TSNE", out.dir=tmp,
	html.open=TRUE, title="Cell-cell interaction within pC", thr=25)
 ```

**Comment by qq2006tom-cmd** [comment]
Hi Koki,

Finally, it works. Thank you so much for your patience and guidance. I really appreciate it.

All the best

Tao

**Comment by michelesilvestro** [comment]
Hi Koki,
thank you very much for developing scTensor, it's extremely interesting and a powerful tool.
I found the info in this thread very useful and I almost managed to make it work on my dataset.

I have a problem here:

> cellCellDecomp(sce, ranks=c(3,3))
Error in f(input, LR, celltypes, ranks, rank, centering, mergeas, outer,  : 
  Please specify the ranks[1] as an smaller value

Could you please advise?
Thank you very much. I truly appreciate your help
