### ISSUE TITLE
Running out of Vector Memory

### ISSUE THREAD

**Issue by keshav12397** [rikenbit/scTensor#12]
Hi!

Thanks for this package, super excited to use it. I've gone through all the steps it works great, however at the very end when I do CellCellDecomp the process takes very long to run and while it says a tensor is created, it then follows up with 2 messages saying “Error: vector memory exhausted (limit reached?).”
I've tried forcing RStudio to use more memory but it still gives me the same error. I was doubtful it's a limitation of my machine since it's a new Macbook Pro with 16gb RAM, so I'm unsure if I'm just doing something wrong. Any help would be appreciated, thank you!

**Comment by kokitsuyuzaki** [comment]
Hi,

Could you tell me the size of CCI tensor?
How many celltypes are analyzed in your analysis?

Koki

**Comment by kokitsuyuzaki** [comment]
In scTensor, CCI-tensor is descibed as 

**No. of cell types × No. of cell types × No. of Ligand-Receptor pairs**

and if the number of cell types is large, the size of tensor also becomes large.

I'm now working on the problem by using a sparse tensor format, if you are not in a hurry, please wait until the future version of scTensor.

Koki

**Comment by keshav12397** [comment]
Hi,

Initially I tried it with 18 cell types which is what caused the error, but now trying with fewer cell types it works great. Thanks for the reply and I look forward to seeing your future work!
