### ISSUE TITLE
Error: creating SingleCellExperiment object after geneID conversion

### ISSUE THREAD

**Issue by skim245** [rikenbit/scTensor#15]
I'm having a problem after converting gene symbol to NCBI Gene ID (ENTREZID)
and re-creating SingleCellExperiment object 

sce <- SingleCellExperiment(assays=list(counts = for_sc))

Error in validObject(.Object) : 
  invalid class "SummarizedExperiment" object: 
    'names(x)' must be NULL or a character vector with no attributes

**Comment by kokitsuyuzaki** [comment]
Hi, 

SummarizedExperiment object cannot be directly used for the input of SingleCellExperiment, so you have to specify the expression matrix instead.
https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html

Please check the assays(for_sc)$counts is matrix object.
The  matrix can be specified  for the input of SingleCellExperiment.

```r
is(assays(for_sc)$counts)
sce <- SingleCellExperiment(assays=list(counts = assays(for_sc)$counts))
```

Koki
