### ISSUE TITLE
typical runtime

### ISSUE THREAD

**Issue by rlittman16** [rikenbit/scTensor#17]
Hi,

I'm interested in using this tool, for finding RL relationships between subtypes ~300. I'm currently including all genes, and seeing what comes up. What is the typical run time for this? For both cellCellRanks and CellCellDecomp. 

Thanks!
Russell

**Comment by kokitsuyuzaki** [comment]
> 300 subtypes

scTensor cannot be performed against such huge datasets.
We usually use scTensor 10 to 30 celltypes.
