### ISSUE TITLE
How to visualize cci as lrgene to edge, and cell type as node.

### ISSUE THREAD

**Issue by knagakura** [rikenbit/scTensor#18]
Hi, 

I can visualize my data to cci as lrgenes are nodes, and detected relationships are edges.
But I want to visualize the cci as lr-genes pair is edge, and cell-types are edge.

Is there any function to visualize it ?
or Is there any data to visualize such way?

Thanks!

Kazuya Nagakura

**Comment by kokitsuyuzaki** [comment]
> the cci as lr-genes pair is edge, and cell-types are edge

Sorry, I cannot understand this part...
