### ISSUE TITLE
How to find the degree of the size of the LR-pair in the LR-pair pattern in the output files

### ISSUE THREAD

**Issue by kevin198930** [rikenbit/scTensor#19]
Hello,

Thank you for developing this interesting package. I have been using the HTML report interpretation vignette to try and find the degree of the size of the LR-pair in the LR-pair pattern where it is quantified as P-value and Q-value. I would like to extract the top 20 L-R pairs for each L-R pair pattern. Specifically, like the figure in the HTML report interpretation vignette that contains the rank, ligand gene, receptor gene, L-R pair factor value, p-value, and q-value. Is this within the html report that is generated or within the reanalysis.RData object? If it is in the reanalysis.RData object, which data object, for example upon loading in RStudio I see objects g, LR, out.vecLR, sce, twoD? Also, an error was generated when I ran my script for scTensor, although most of the files were generated, except the html ones. The error was as follows:

Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

Thank you for your help!

**Comment by kokitsuyuzaki** [comment]
Yes, such information is stored in out.vecLR in reanalysis.RData.

Sorry, I cannot specify the reason of the error only by seeing the message.
To reproduce your error in my environment, send the following information.

1. Source code
2. Minimum data
3. The result of sessionInfo()

**Comment by kevin198930** [comment]
Thank you for your response. I am utilizing data that contains 13 unique cell types and have reduced the gene number to include only the 3000 highly variable genes. I end up with an error during the CellCellDecomp as follows:

13 * 13 * 5832 Tensor is created, which generates an error "cannot allocate vector of size 23.1Gb. 

I used the CellCellRanks rank estimation function to determine the number of ranks to use. 

rks <- cellCellRanks(sce, assayNames="logcounts")

print(rks$selected)
[1] 7 7
#CellCellDecomposition
set.seed(1234)
cellCellDecomp(sce, ranks=rks$selected, assayNames="logcounts")
13 * 13 * 5832 Tensor is created
cannot allocate vector of size 23.1Gb

Thank you for your help!

**Comment by kokitsuyuzaki** [comment]
> cannot allocate vector of size 23.1Gb

means that your data is too large and cannot expand on the memory space.
To reduce the size, you have to reduce the number of cell types (n=13), the number of ligand-receptor (n=5832), or both.
How did you set the parameter of cellCellSetting()?

**Comment by kevin198930** [comment]
I set the parameter of CellCellSetting() as recommended in the vignette, cellCellSetting(sce, LRBase.Hsa.eg.db, label_Astro). The label_Astro variable is the cell type annotation metadata column from my Seurat object:

label_Astro <- as.character(astro_merged_subsets$CellType)

I have reduced the number of genes to only the highly variable genes (3000 genes) as well as changed the cell type annotation to include only 8 unique cell types. This allowed the scTensor script to run successfully up to the point of the CellCellReport() step. The script took overnight to run ~8-9 hours and failed with the error:

Hyper-links are embedded...
GO-Enrichment Analysis is running...(1/3)
'select()' returned 1:many mapping between keys and columns
GO-Enrichment Analysis is running...(2/3)
'select()' returned 1:many mapping between keys and columns
GO-Enrichment Analysis is running...(3/3)
'select()' returned 1:many mapping between keys and columns
MeSH-Enrichment Analysis is running...(1/16)
MeSH-Enrichment Analysis is running...(2/16)
MeSH-Enrichment Analysis is running...(3/16)
MeSH-Enrichment Analysis is running...(4/16)
MeSH-Enrichment Analysis is running...(5/16)
MeSH-Enrichment Analysis is running...(6/16)
MeSH-Enrichment Analysis is running...(7/16)
MeSH-Enrichment Analysis is running...(8/16)
MeSH-Enrichment Analysis is running...(9/16)
MeSH-Enrichment Analysis is running...(10/16)
MeSH-Enrichment Analysis is running...(11/16)
MeSH-Enrichment Analysis is running...(12/16)
MeSH-Enrichment Analysis is running...(13/16)
MeSH-Enrichment Analysis is running...(14/16)
MeSH-Enrichment Analysis is running...(15/16)
MeSH-Enrichment Analysis is running...(16/16)
Reactome-Enrichment Analysis is running...(1/1)
DO-Enrichment Analysis is running...(1/1)
NCG-Enrichment Analysis is running...(1/1)
DGN-Enrichment Analysis is running...(1/1)
Hyper-links are embedded...
Error in plot.new() : 
  could not open the file '~//figures/GeneHypergraph.png'
Calls: cellCellReport ... .geneHyperGraphPlot_2 -> plot.igraph -> plot -> plot.default -> plot.new
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

**Comment by kokitsuyuzaki** [comment]
If `cellCellDecomp` cannot be performed properly, `cellCellReport` cannot be performed.

How about setting `lr.evidence` of `cellCellSetting` as known, which means only known ligand-receptor pairs are used and putative pairs are rejected?

We collected some known L-R databases.

cf. 
https://github.com/rikenbit/scTensor/blob/4f6f68904cde9657ab6fac3fe7956bb5c7485f22/R/cellCellReport-internal.R#L79
