### ISSUE TITLE
CCI-strength thresholds and patterns

### ISSUE THREAD

**Issue by ycl6** [rikenbit/scTensor#20]
Hi,

I am wondering how one can control the threshold for CCI-strength that decide which or how many (Ligand-Cell, Receptor-Cell, LR-pair) Patterns to report in the HTML report.

In this example CCI-wise Hypergraph:
![CCIHypergraph](https://user-images.githubusercontent.com/9032946/152884973-4733ef97-58a7-455f-9f26-960625394454.png)

The report shows 4 (Ligand-Cell, Receptor-Cell, LR-pair) Patterns ranked by CCI-strength. Is it possible to adjust the threshold to include more patterns, such as (4,3,) -related L-R Pairs?
- (1,3,) -related L-R Pairs : (8.77%)
- (1,4,) -related L-R Pairs : (6.9%)
- (1,5,) -related L-R Pairs : (6.58%)
- (1,1,) -related L-R Pairs : (6.48%)

**Comment by kokitsuyuzaki** [comment]
Hi, @ycl6 

Which version of scTensor are you using?

**Comment by ycl6** [comment]
Hi @kokitsuyuzaki 

I am using 2.4.1. I figured out I can change the `thr` param in `cellCellReport` to adjust the number of LRs returned. The code below from `cellCellReport-NTD.R` and `cellCellReport-NTD2.R` would calculate the number of LRs based on the `thr` used. 

```R
    index <- metadata(sce)$sctensor$index
    corevalue <- index[, "Value"]
    corevalue <- corevalue / sum(corevalue) * 100
    selected <- which(cumsum(corevalue) <= thr)
```

I think it will be useful to have a helper function where user can run to identify the number of LRs one can get with a certain `thr` before running `cellCellReport` as it can take some time to create the final report.

I also think it will be useful to have functions to pre-plot some figures, for example the LC-patterns heatmap, RC-patterns heatmap and CCI-wise hypergraph, and to help user decides the `thr` before generate the final report with `cellCellReport`. If you also agree, I can contribute some pull requests to the package.

**Comment by kokitsuyuzaki** [comment]
> thr

Yes, that is the correct understanding.

> helper function

Thanks for the suggestion.
However, the functionality is almost the same as `cellCellReport`, so I may not create such a function.
As for your concern about the processing speed of `cellCellReport`, since a lot of time is spent on enrichment analysis, if you skip all the enrichment analyses as shown below, you can get plots quickly, so please try that first.

```
cellCellReport(...
    goenrich=FALSE, meshenrich=FALSE, reactomeenrich=FALSE,
    doenrich=FALSE, ncgenrich=FALSE, dgnenrich=FALSE)
```

Koki

**Comment by ycl6** [comment]
Hi @kokitsuyuzaki 

About my suggestions, my rational is for users to be able to examine the key metrics after performing CCI-tensor construction and decomposition within R directly instead of having to create a HTML report and read about them on a browser.

I'll close this issue as my original query has been answered, thanks!
