### ISSUE TITLE
Question with scTensor

### ISSUE THREAD

**Issue by ShellyCoder** [rikenbit/scTensor#6]
1.  I have run the scTensor with GermMale dataset. But it seems that the website isn't in use, performing cellCellReport function.

2.  I have no idea about where the attribute ' in SingleCellExperiment Object ' stored the final CCI[receptor-ligand] interaction and their score.
![1 %B KSFYF7U7$J V9ZL_ 2](https://user-images.githubusercontent.com/49678387/63651851-05e8c300-c78c-11e9-9f16-b849a1f97cdf.png)

I am willing to use your method in my own scRNA-dataset, but get stacked in something.
Thanks in advance, if you can reply me in convenience.

**Comment by ShellyCoder** [comment]
Hi:
  1.Now i got the lrpair in the sce object. But how can i infer the specific L-R in the cellA-cellB. 
  2.All i got is a array in some LR (eg. , , LR = 3479_187) , then i'am confuzed about the Lpattern and Rpattern (eg. Dim1,Dim2,Dim3...).
  3.Since I am a biological researcher, my knowledge of mathematics is very weak. I just want the relationship of L-R between different types of cells. Could me have some advice?
![I}SH}4~(ZW9} P2D05VDG(C](https://user-images.githubusercontent.com/49678387/63680025-447e8c00-c825-11e9-9958-8362989cac61.png)

Sincerely.

**Comment by kokitsuyuzaki** [comment]
Hi,

Thanks for having interesting with scTensor.

Yes, as you showed, the result of scTensor is saved in metadata slot of singleCellExperiment object.

Could you tell me the verion of R and scTensor?
Recent algorithm of scTensor is changed as a different model,
the way to explain the result depends on the version.

Koki

**Comment by ShellyCoder** [comment]
Appreciate your reply.

Here is my version about R and scTensor.

![C542}SQTLUPDLA}NWX@@$R0](https://user-images.githubusercontent.com/49678387/64073198-3620ec00-cccd-11e9-9abe-31d38bdbeda9.png)

And with the metadata i have no idea about how to get scores about L-R of a specific cell type. 


![6ZZ_T5~KI92TLA)AHKSFV~H](https://user-images.githubusercontent.com/49678387/64073280-18a05200-ccce-11e9-8e24-91075c3b0e33.png)

BTW, this project is fantastic!

**Comment by kokitsuyuzaki** [comment]
Thanks!

Ok, you're working on the most recent version of scTensor,
and in this version, non-negative Tucker2 decomposition is a newly introduced.

> the Lpattern and Rpattern (eg. Dim1,Dim2,Dim3...).

**Lpattern** means some patterns of ligand-expressing celltypes.
These patterns are calculated by the tensor decomposition.
The number of patterns is the first parameter you specified in **cellCellDecomp()** function.
For example, you specified 5 as the parameter, 5 of patterns are generated (Dim1,2,...,5).

In the same way, **Rpattern** means some patterns of receptor-expressing celltypes and the number of patterns is the second paramter of **cellCellDecomp()**.

I'm now assuming that you finished **cellCellReport()** and you already have the HTML report.
You can confirm the Lpattern and Rpattern in **"3. Ligand-Cell Patterns"** and **"4. Receptor-Cell Patterns"** in the report.

I also created the vignette to interpret the HTML report,
so please check this.
https://bioconductor.org/packages/devel/bioc/vignettes/scTensor/inst/doc/scTensor_2_Report_Interpretation.html

> how can i infer the specific L-R in the cellA-cellB.

> the relationship of L-R between different types of cells

If the x-th pattern in **Lpattern** is related to cellA and if the y-th pattern in **Rpattern** is related to cellB, the CCI between these patterns <(x,y,)-CCI> is what you want.

The related L-R pairs can be confirmed in **"7. (Ligand-Cell,Receptor-Cell)-related L-R Pairs"** in the report.
For example, if you have interested in (x,y,)-CCI, you will confirm the **"(x,y,)-related L-R Pairs"**.

All the combination of Lpattern and Rpattern can be confirmed in **"5. CCI-wise Hypergraph"**.

Please note that scTensor does not pair specific cell types in advance.
Instead, the pairs are extracted based on the L-R coexpression in data-driven way without any assumption of cell-cell pairing.


Koki

**Comment by ShellyCoder** [comment]
Thanks for your meaningful reply.

As you mentioned above:
     "If the x-th pattern in Lpattern is related to cellA and if the y-th pattern in Rpattern is related to 
     cellB "

1.  How can i now the probability about x-th pattern is related to cellA？

     For example, as we can see in the square of the following pic. According to 'Male_Soma_1', does 
     the decimal  -- （‘0.247144602’，‘0.109680271’，‘0.008325557’，‘0.043037610’）measure the 
     probability about Lpattern about specific cell type 'Male_Soma_1' ? And is there a threshold 
     to filter the Dim ?  And the same way to  Rpattern.

![PA1X2ITX`LD6B}~9Z6)HGJ7](https://user-images.githubusercontent.com/49678387/64486329-6123b680-d25e-11e9-8999-c61cc5c72596.png)



2. The decimal in the 'sce@metadata$sctensor$lrpair@data' as shown below measure the strength of 
    L-R in the specific cell type or it's just the p-value to represent the significance ? And if that, how 
   can i measure the strength, the sum of expression in the array or something else.


![`BJW@(D6%4{J112~WGIA`FW](https://user-images.githubusercontent.com/49678387/64486220-b9f24f80-d25c-11e9-86f4-46a1ceba43c0.png)


My thanks again!
Live long and prosper!

**Comment by ShellyCoder** [comment]
I have the same error with other users. -- 'Error: failed to load resource' with the function cellCellReport(). 

So i must figure out the question below, then could infer the L-R of cell-cell based on the result of  cellCellDecomp().

**Comment by kokitsuyuzaki** [comment]
> 1. How can i now the probability about x-th pattern is related to cellA？

The values in the x-th pattern have no meaning of probability, 
it's just the scores of the relatedness between the x-th pattern and the cell type A.
For the practicality, these values are binarized by clustering,
converted to 0 (Negative) or 1 (Positive), and visualized in the HTML report.

> 2. The decimal in the 'sce@metadata$sctensor$lrpair@data' as shown below measure the strength of
L-R in the specific cell type or it's just the p-value to represent the significance ?

Yes, it's the strength of L-R in the specific cell type.

> And if that, how
can i measure the strength, the sum of expression in the array or something else.

Sorry, could you explain in more detail?


> 'Error: failed to load resource' with the function cellCellReport().

It seems the error of AnnotationHub.
Could you check this issue?
https://github.com/rikenbit/scTensor/issues/8

Koki

**Comment by ShellyCoder** [comment]
Appreciate your focus!

> Yes, it's the strength of L-R in the specific cell type.

1. And i also have a puzzle. Can we have a thr to filter score in the sce@metadata$sctensor$lrpair ? 

> It seems the error of AnnotationHub.
    Could you check this issue?

2. Yes, it's just an error of AnnotationHub. Considering the dependence, it will be better, if you can pre-load in your R package.

Sincerely.

**Comment by kokitsuyuzaki** [comment]
No, I didn't set the thr such as p-value.
Actually, the binarization is sometimes conservative,
and some interesting patterns may be overlooked.
I'll think about the better method.

Could you resolve the problem of AnnotationHub?
Did you perform the following script?

```r
library("AnnotationHub")
ah <- AnnotationHub()
ah[["AH70572"]]
```

Koki
