### ISSUE TITLE
error about cellCellReport

### ISSUE THREAD

**Issue by Lyuzu** [rikenbit/scTensor#8]
Dear Developer:
 I am trying to analyse L-R connections in my single cell data by scTensor 1.0.12 under R version 3.6.1. cellCellDecomp function worked with no problem though there was an error when generating a html report like below:

- Input data matrix may contains 7 gene symbols because the name contains some alphabets.
scTensor uses only NCBI Gene IDs for now.
Here, the gene symbols are removed and remaining 235 NCBI Gene IDs are used for scTensor next step.
7 * 7 * 84 Tensor is created
snapshotDate(): 2019-05-02
downloading 1 resources
retrieving 1 resource
  |============================                                                                                                          |  21%Error: failed to load resource
  name: AH70572
  title: org.Hs.eg.db.sqlite
  reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
  web resource path: 'https://annotationhub.bioconductor.org/fetch/77318'
  local file path: 'C:\Users\zju\AppData\Local\AnnotationHub\AnnotationHub\Cache/22e4c562022fd_77318'
  reason: Recv failure: Connection was reset 
2: bfcadd() failed; resource removed
  rid: BFC6
  fpath: 'https://annotationhub.bioconductor.org/fetch/77318'
  reason: download failed 
3: download failed
  hub path: 'https://annotationhub.bioconductor.org/fetch/77318'
  cache resource: 'AH70572 : 77318'
  reason: bfcadd() failed; see warnings() 

 
I tried to copy and paste the mentioned download address and download the file on my chrome web browser. It failed again and again and again. I asked others(in China or Australia) to help downloading but failed again. 
So I am curious what's the problem and whether other people meet the same problem as me.
Looking forward to your reply. Thank you!

**Comment by kokitsuyuzaki** [comment]
Hi, 

Thanks for having interest with my package.

scTensor internally uses AnnotationHub package to retrieve the gene annotation database in each organism.
Since this test data is about Homo sapiens,
AH70572 should be downloaded but it seems that the download process was failed for some reasons.
Could you confirm that  this code can be performed properly,

```r
library("AnnotationHub")
ah <- AnnotationHub()
ah[["AH70572"]]
```

and then perform cellCellReport() again?

Once this code is performed, the corresponding database is saved as BiocFileCache,
https://bioconductor.org/packages/release/bioc/html/BiocFileCache.html
and we do not need to repeatedly download it anymore.

Koki

**Comment by Lyuzu** [comment]
Dear Koki:
Thanks for your reply. I ran the codes you mentioned and the download process still failed as below
> > ah[["AH70572"]]
> downloading 1 resources
> retrieving 1 resource
>   |============================                                                                                                          |  21%Error: failed to load resource
>   name: AH70572
>   title: org.Hs.eg.db.sqlite
>   reason: 1 resources failed to download
> In addition: Warning messages:
> 1: download failed
>   web resource path: 'https://annotationhub.bioconductor.org/fetch/77318'
>   local file path: 'C:\Users\zju\AppData\Local\AnnotationHub\AnnotationHub\Cache/3a9c438b7308_77318'
>   reason: Recv failure: Connection was reset 
> 2: bfcadd() failed; resource removed
>   rid: BFC13
>   fpath: 'https://annotationhub.bioconductor.org/fetch/77318'
>   reason: download failed 
> 3: download failed
>   hub path: 'https://annotationhub.bioconductor.org/fetch/77318'
>   cache resource: 'AH70572 : 77318'
>   reason: bfcadd() failed; see warnings()

Also, with other's help, I downloaded "org.Hs.eg.db.sqlite" file and tried to load it locally refering to http://www.bioconductor.org/packages/devel/bioc/manuals/AnnotationHub/man/AnnotationHub.pdf (page 10/13) as below but the problem still existed.

```
> hub <- AnnotationHub()
snapshotDate(): 2019-05-02
> 
> bfc <- AnnotationHub:::.get_cache(hub)
> bfcadd(bfc, fpath="D:/org.Hs.eg.db.sqlite",rname="AH70572 : 77318")
                                                                                                 BFC14 
"C:\\Users\\zju\\AppData\\Local\\AnnotationHub\\AnnotationHub\\Cache/3a9c5e0c5831_org.Hs.eg.db.sqlite" 
```
> > ah <- AnnotationHub()
> snapshotDate(): 2019-05-02
> > ah[["AH70572"]]
> downloading 1 resources
> retrieving 1 resource
> Error: failed to load resource
>   name: AH70572
>   title: org.Hs.eg.db.sqlite
>   reason: 1 resources failed to download
> In addition: Warning message:
> download failed
>   hub path: 'https://annotationhub.bioconductor.org/fetch/77318'
>   cache resource: 'AH70572 : 77318'
>   reason: Corrupt Cache: resource id
>   More than one entry in cache for: AH70572 : 77318
>   See vignette section on corrupt cache 

Maybe I need to utilize the result of  cellCellDecomp and generate the results manually ?

**Comment by kokitsuyuzaki** [comment]
Could you also ask this issue to the Bioconductor support site?
https://support.bioconductor.org

I imagine this part means that the curl command is not performed properly.

```
reason: Recv failure: Connection was reset
```

https://stackoverflow.com/questions/36735630/curl-56-recv-failure-connection-was-reset?rq=1

**Comment by Lyuzu** [comment]
Dear Koki:
Thanks for your suggestion. I will try that.
