### ISSUE TITLE
cannot complete cellCellDecomp

### ISSUE THREAD

**Issue by Jami-Erickson** [rikenbit/scTensor#9]
Hello Developer,

I am just trying out your package using a 10x demo data set (8k PBMC). I created a sce from a Seurat object. I was able to run cellCellSetting, but when I Run cellCellDecomp I am getting an error that I am not sure how to resolve. The error is: Error in rep(0, nrow(input)) : invalid 'times' argument.

<img width="581" alt="Screen Shot 2019-09-20 at 6 26 48 PM" src="https://user-images.githubusercontent.com/42222189/65366081-375e7e00-dbd4-11e9-8a0f-799c0826be60.png">

<img width="721" alt="Screen Shot 2019-09-20 at 6 27 19 PM" src="https://user-images.githubusercontent.com/42222189/65366087-4b09e480-dbd4-11e9-9024-dc94b36f59b0.png">
<img width="864" alt="Screen Shot 2019-09-20 at 6 28 23 PM" src="https://user-images.githubusercontent.com/42222189/65366105-6ffe5780-dbd4-11e9-824b-c59bd1b1bd24.png">
<img width="984" alt="Screen Shot 2019-09-20 at 6 28 51 PM" src="https://user-images.githubusercontent.com/42222189/65366115-80aecd80-dbd4-11e9-9a0a-b04e162999e4.png">

I am relatively new in R, so I am sorry if this is a trivial issue and I am missing something obvious.

**Comment by kokitsuyuzaki** [comment]
Hi, @Jami-Erickson

Thanks for having interest in my package.

The row names of the scePBMC_8k are Gene Symbol, but scTensor assumes that the row names are NCBI Gene ID.

Such ID conversion is explained in the vignette of scTensor (https://bioconductor.org/packages/release/bioc/vignettes/scTensor/inst/doc/scTensor_1_Data_format_ID_Conversion.html), so please check it.

Koki

**Comment by Jami-Erickson** [comment]
Hi Koki,

thanks for getting back to me so quickly! I am excited to implement this package, but ran into another issue. 

when I use the convertToNCBIGeneID initially to create a matrix, that I will turn into a Seurat object so I can calculate PCA and UMAP parameters: 
<img width="865" alt="Screen Shot 2019-09-30 at 5 04 42 PM" src="https://user-images.githubusercontent.com/42222189/65925129-67600b00-e3a4-11e9-9f6f-922bf4ba2d80.png">

I cannot turn this object into a single cell experiment object as I get an error of row names not being a character. 
<img width="829" alt="Screen Shot 2019-09-30 at 5 07 39 PM" src="https://user-images.githubusercontent.com/42222189/65925241-d0e01980-e3a4-11e9-8f81-4da00bc4251f.png">

here is the str of the object:
<img width="946" alt="Screen Shot 2019-09-30 at 5 11 09 PM" src="https://user-images.githubusercontent.com/42222189/65925346-4fd55200-e3a5-11e9-80aa-c1ee5e534434.png">

do you have any suggestions on how I can get around this?

Another issue I ran into, is that not all genes remain present when I use convertToNCBIGeneID (I go from 18340 genes, to 14754 genes). when I make a UMAP I still get the same clusters, so I don't think its too big of an issue, but something I thought people should be aware of. 

Thanks again for your help!
-Jami

**Comment by Jami-Erickson** [comment]
Hi Koki,

I am now having a problem with my sce file. I am getting an error that my color vector needs to be the same length as nrow(assay(sce)). 

<img width="567" alt="Screen Shot 2019-10-02 at 12 50 36 PM" src="https://user-images.githubusercontent.com/42222189/66076707-3d792680-e513-11e9-85d2-331e28f7e3c9.png">

The problem I'm having is that the sce is calling my genes (nrow(assay(sce)) = 14754) , not my cells (8380). is there any way to change the identity that called? I'm assuming its important that each cell is assigned a color, not each gene. 

Thanks for your help!
-Jami

**Comment by kokitsuyuzaki** [comment]
Hi, @Jami-Erickson

Could you send me the results of this code?

```r
length(Label3PBMC_8k)
length(namesPBMC_8k)
length(unique(Label3PBMC_8k))
length(unique(namesPBMC_8k))
nrow(assay(sce))
ncol(assay(sce))
is(assay(sce))
assay(sce)[1:4,1:5]
```

Koki
